### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hjone72** [datkinson13/Student_Management_System#17]
Would anyone object to a slight adjustment to our current permissions setup? I propose to replace the two tables we currently have, `administrators` and `facilitators` as they aren't adding any extra info to our Users, with the following two tables;

```
Schema::create('roles', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name');
    $table->string('slug')->unique();
    $table->jsonb('permissions')->default('{}');
    $table->timestamps();
});

Schema::create('role_users', function (Blueprint $table) {
    $table->unsignedInteger('user_id');
    $table->unsignedInteger('role_id');
    $table->timestamps();

    $table->unique(['user_id','role_id']);
    $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
    $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
});
``` 

This will make permissions easier to understand and provide an obvious pathway to create a granular permissions system in a later (outside SCU) project. The change won't actually require much work but I believe it will provide benefits.

This is a change from our original schema so I wanted to check with everyone, we may also need "permission" from the course coordinator.

**Comment by datkinson13** [comment]
That sounds good, we aren't using Admin/Facilitator yet, so we aren't losing any functionality... Are we just going to control the permissions within the controller, rather than set specific functions on the class itself not available to other sub-classes of User? 

For example:

public function destroy () {
   IF (Admin)
      $user->delete();
   ELSEIF(BasicUser)
      break;
}

Actually, that looks like it will be a lot easier to manage... so it's your call :)

We will need to bring in a model later for the 'employee-roles' with the competency management, maybe we should name these roles as 'system-roles', just to avoid any confusion?

**Comment by hjone72** [comment]
> public function destroy () {
IF (Admin)
$user->delete();
ELSEIF(BasicUser)
break;
}

Not quite, but kinda. It's done using Authorization, specifically gates and policies. I've not done anything with them before but it doesn't look that difficult.

example:
```
    Gate::define('change-permissions', function ($user) {
        return $user->inRole('administrator');
    });
```

See more [here](https://laravel.com/docs/5.5/authorization)

> We will need to bring in a model later for the 'employee-roles' with the competency management, maybe we should name these roles as 'system-roles', just to avoid any confusion?

system-roles sounds good. Really makes it sounds like a system function/permission.

**Comment by hjone72** [comment]
Hmmm just re-thinking about the table name. I'm going to still use `system-roles` but it does break the pivot table standard naming.

**Comment by datkinson13** [comment]
Ahhh yeah, that's awesome! Kind of like an access/resource matrix?

Yeah ok, I'm happy with whatever naming conventions :)
