### ISSUE TITLE
Course creation

### ISSUE THREAD

**Issue by hjone72** [datkinson13/Student_Management_System#25]
Users who have permissions should be able to create a course.

**Comment by hjone72** [comment]
We need to think about what would happen if a facilitator stopped being a facilitator or deleted their account.

Currently a course has a user_id, what if that user left? what if they worked part time with another facilitator? How do we assign permissions to two facilitators to control the course?
Or is all of that outside the scope?

**Comment by hjone72** [comment]
Mostly completed. You can add courses but there is no validation. No gates have been configured yet either.

**Comment by emilyholmes** [comment]
That's the reason you 'drop' a name from a table, not 'delete' That way it doesn't break old data, but they're removed from the list.

**Comment by hjone72** [comment]
> That's the reason you 'drop' a name from a table, not 'delete' That way it doesn't break old data, but they're removed from the list.

What do you mean?

**Comment by emilyholmes** [comment]
I'm sorry. I'm confusing things, ignore me
