### ISSUE TITLE
Enrolment - Database Migration Form

### ISSUE THREAD

**Issue by datkinson13** [datkinson13/Student_Management_System#35]
Update enrolment migration form with relevant fields:
- CompletedDate
- ExpiryDate
- EnrolmentStatus
- Anything else?

**Comment by hjone72** [comment]
We'll need to also update course with info about how long the course is valid for.

**Comment by hjone72** [comment]
> EnrolmentStatus

Should EnrolmentStatus be controlled by another table and actually be EnrolmentStatus_id?

**Comment by hjone72** [comment]
I think this is completed.
